
export declare namespace DOTA{
	export enum GameState {
	  DOTA_GAMERULES_STATE_INIT = 0,
	  DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD = 1,
	  DOTA_GAMERULES_STATE_HERO_SELECTION = 3,
	  DOTA_GAMERULES_STATE_STRATEGY_TIME = 4,
	  DOTA_GAMERULES_STATE_PRE_GAME = 7,
	  DOTA_GAMERULES_STATE_GAME_IN_PROGRESS = 8,
	  DOTA_GAMERULES_STATE_POST_GAME = 9,
	  DOTA_GAMERULES_STATE_DISCONNECT = 10,
	  DOTA_GAMERULES_STATE_TEAM_SHOWCASE = 5,
	  DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP = 2,
	  DOTA_GAMERULES_STATE_WAIT_FOR_MAP_TO_LOAD = 6
	}
  }